---
- name: Backup running config for IPA Final
  hosts: routers
  gather_facts: false

  vars:
    # เราจะใช้ 'inventory_hostname' ซึ่งก็คือ IP ที่ถูก limit มา
    backup_filename: "show_run_66070246_{{ target_ip }}.txt"

  tasks:
    - name: Get running-config from device
      cisco.ios.ios_command:
        commands:
          - show run
      register: config

    - name: Save running-config to local file
      ansible.builtin.copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_filename }}" # ใช้ตัวแปรชื่อไฟล์
      delegate_to: localhost